version: '3.9'

services:

  ts-node-docker:
    build: .
    command: npm run dev
    networks:
      - bridge-network
    depends_on:
      - rabbitmq
    volumes:
      - ./nodemon.json:/app/nodemon.json
      - ./src:/app/src

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
